<a href="https://colab.research.google.com/github/rachelkd/geering-up/blob/main/1_2-introduction-to-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Section 1: Simple variables

There are different **types** of variables.

A variable can either be a type:

- String (text and characters)
  - Note: Python does not have a distinct `char` type unlike Java!
- Integer `int`
- Float `float`
- Boolean `bool`
  - `True` or `False`

We use an **assignment statement** to initialize, declare, and/or update variables.

- Variable name left of `=` sign
- Expression/value is right of `=`

An **expression** is a combination of values, variables, operators, and function calls that the Python interpreter evaluates to produce a single value or object.

Examples:

```python
3.0 + 1.5
True
8
(True or False) and True
```


In [3]:
my_string = "test string"
my_integer = 4
my_float = 2.1
my_boolean = True
null_variable = None

We can check the type of a **variable** or **expression** by calling the `type` function and passing in the variable name or expression as a **parameter**.

In [4]:
print(type(my_string))
print(type(my_integer))
print(type(my_float))
print(type(my_boolean))
print(type(null_variable))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'NoneType'>


In [5]:
# TODO: Create a variable called my_type that stores the type of the type of any value (i.e., <class 'type'>)
# Replace ... with your expression!
#
# HINT 1: One way to do this is to use the type() function TWICE.
# HINT 2: You can use any variable (e.g., my_string) as the inner argument to type().
# HINT 3: Use the print() function once to display the result.

my_type = ...

# Do not edit
print(my_type)

Ellipsis


In [6]:
#@title Test Cases (DO NOT EDIT)
assert my_type is type, "Expected my_type to be <class 'type'>"

AssertionError: Expected my_type to be <class 'type'>

# Section 2: Comments and displaying text

In [ ]:
# printing my number variables
print(my_integer)
print(my_float)

# Below is a multi-line comment
'''
Display my string variable
'''
my_string


# TODO: Use a keyboard shortcut (Ctrl + /) to quickly comment/uncomment lines of code
# TIP: You can highlight multiple lines to comment them all at once
Comment this line using the keyboard shortcut
And this line
And this line

#### Aside: What is the difference between `print(my_string)` and just `my_string`?

In Google Colab, you can see a variable's value by just writing its name, like this:

```python
my_string = "hello"
my_string  # This will show: 'hello'
```

If you write:

```python
print(my_string)  # This will also show: hello
```
The difference is:

- `print(my_string)` always shows the value, no matter where you use it (in a script, notebook, or program).

- Just writing `my_string` only works in notebooks or the *Python shell*
  - It won't show anything if you run it in a regular program.

# Section 3: If statements

We use if statements if we only want to run code if a certain condition is true or false.

Example:
- Print "You got an A!" if the `grade` is 85 or higher

In [ ]:
my_new_number = 10

my_integer > my_new_number

In [ ]:
# TODO: What number will be printed when this code is run?
# Set answer to be the STRING of the number

answer = ...


print("greater number: ")

if (my_integer > my_new_number):
  print(my_integer)

print(my_new_number)

In [ ]:
#@title Test case (DO NOT EDIT)
assert answer == "10", "Expected answer to be \"10\""

In [ ]:
# Change my_new_number so that the if condition is true

my_new_number = ...



print("greater number: ")

if (my_integer > my_new_number):
  print(my_integer)
else:
  print(my_new_number)

# Section 4: Lists

We use **lists** when we want to store a bunch of things together in one place.

Think of a list like a basket — it can hold:

- Numbers: `[1, 2, 3, 4]`
- Words: `["apple", "banana", "cherry"]`
- Even a mix: `[7, "cat", True]`

In [ ]:
my_list = []
my_string_list = ["first", "second", "third"]
my_integer_list = [1,2,3,4,5]

my_integer_list

#### Accessing members/elements in our list

In Python, we use **zero-based indexing**. This means the first item is at position 0, the second at 1, and so on.

In [ ]:
my_string_list[0]

In [ ]:
# TODO: Create a variable called fourth that is the number 4 from my_integer_list

fourth = ...  # fill in blank

#### `len` function

We can access the length of our list using the `len` function and passing in our list as an argument/parameter.

In [ ]:
len(my_integer_list)

#### Other Useful List Functions

- `append(item)` - adds to the end of the list
- `insert(index, item)` - adds at a specific spot
- `pop()` - removes and returns the last item
- `remove(item)` - removes the first matching item
- `sort()` - sorts the list in order
- `reverse()` - reverses the list

Note: these are special functions called **methods**.
- Method: a function that *belongs to* an object

We call methods slightly differently:

```python
my_list = [1, 2, 3]
my_list.append(4)
```

In [ ]:
# TODO: Remove 2 and 5 from my_list only using the pop function
#
# TIP: Google Colab tells you what arguments a function can take if you hover
# over the function with your cursor
#
# HINT: pop can take one argument or NO arguments (defaults to last element)


my_list = [1, 2, 3, 4, 5]
...

In [ ]:
#@title Test case (DO NOT EDIT)
assert my_list == [1, 3, 4], "Expected [1, 3, 4], got " + str(my_list)

# Section 5: For Loops

Is there a way to add all elements in our integer list to a variable called `sum`?

In [ ]:
my_integer_list = [1,2,3,4,5]

In [ ]:
sum = my_integer_list[0]
sum = sum + my_integer_list[1]
sum = sum + my_integer_list[2]
sum = sum + my_integer_list[3]
sum = sum + my_integer_list[4]
sum

Is there a better way?

A for loop lets you go through each item in a list one by one.

In [ ]:
loop_sum = 0
for item in my_integer_list:
  loop_sum = loop_sum + item

loop_sum

Sometimes we want to use the index number to get each item in a list:

In [ ]:
loop_sum_2 = 0
for i in range(0, len(my_integer_list)):
  loop_sum_2 = loop_sum_2 + my_integer_list[i]
  print("after " + str(i + 1) + " iteration(s): " + str(loop_sum_2))

In [ ]:
# Testing code that will not work, as the range needs to be integers/ whole numbers
# Uncomment the lines below and see what error you get:

# for i in range(0, my_float):
#   print(i)


In [ ]:
my_list = [9, 9, 9]

for i in range(0, my_integer):
  my_list.append(i)

my_list

## While Loops

**`while` loops** execute a set of statements as long as a condition is true.

Every `for` loop can also be implemented with a `while` loop.

In [ ]:
i = 0
while i < my_integer:
  my_list.append(i)
  i += 1  # same as doing i = i + 1

my_list

IMPORTANT: Notice that we add a number to `i` in the loop body. If we did not change the value of `i`, what would happen?

In [ ]:
i = 0
while i < my_integer:
  print(str(i) + " < " + str(my_integer))
  i += 1

# Section 6: Functions

A function is a block of code which only runs when it is called.

You can pass **parameters** (arguments or data) into a function.

A function can also return data as a result (or not).

We use functions when we want to be able to run the same code over and over again on different inputs of the same type.

The following code uses three `for` loops to get the total sum of all three lists.

In [ ]:
my_first_list = [1,2,3,4,5]
my_second_list = [5,10,40,15]
my_third_list = [3,6,9,12]

total_sum = 0
for item in my_first_list:
  total_sum = total_sum + item

for item in my_second_list:
  total_sum = total_sum + item

for item in my_third_list:
  total_sum = total_sum + item

total_sum

We define a function called `sum_of_list` that returns the sum of every number in the list.

In [ ]:
def sum_of_list(my_list):
  list_sum = 0
  for item in my_list:
      list_sum = list_sum + item
  return list_sum

In [ ]:
# Call the function:
total_function_sum = sum_of_list(my_first_list) + sum_of_list(my_second_list) + sum_of_list(my_third_list)
total_function_sum

In [ ]:
def list_sum_and_items(my_list):
  list_sum = 0
  for item in my_list:
      list_sum = list_sum + item
  return list_sum, my_list

In [ ]:
list_sum_and_items(my_first_list)

All variables that we use inside a function body are LOCAL variables and can only be used in the function.

In `list_sum_and_items`, `list_sum` is a local variable.
We cannot use it outside of the function. See what happens when we run the code block below

In [ ]:
# Produce an error to show function scope
# Uncomment the line below

# list_sum

# Section 7: Using Libraries

Python **libraries** are collections of pre-written code (modules and packages) that provide specific functionalities.

We can use packages to not have to write all code from scratch.

Libraries contain classes, functions, and routines designed to simplify coding, automate tasks, manipulate data, perform computations, and much more.

---

Note:

A Python **class** is a blueprint for creating objects. It defines properties (called attributes) and actions (called methods) that the objects created from the class can have.

An **object** is an instance of a class. It has the actual values for the attributes defined in the class and can use the class's methods.

- e.g., a `list` is a class in Python with methods like `append` and `pop`, which we've used before
- `type` is also a class (it's the class of all classes!)

```python
class Dog:
    def __init__(self, name):
        self.name = name

    def bark(self):
        print(f"{self.name} says woof!")

my_dog = Dog("Buddy")  # Object
my_dog.bark()          # Output: Buddy says woof!
```


### NumPy

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### Why use NumPy?

Python lists are slow.

NumPy provides an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy.

In [7]:
# Import the numpy library
import numpy as np  # we can now refer to the numpy library using "np"

In [8]:
simple_arr = np.array([1, 2, 3, 4, 5])

print(simple_arr)

simple_arr[0]

[1 2 3 4 5]


np.int64(1)

Notice that we index the same way as Python lists (starting from 0).

`simple_arr[0]` evaluates to `np.int64(1)` meaning that the element in `simple_arr` at index 0 is a 64-bit integer.

Below, we have a 2D array (a list of lists)! What does `two_dim_arr[0]` evaluate to?

In [11]:
two_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])

print(two_dim_arr)

print("two_dim_arr[0]: " + str(two_dim_arr[0]))

[[1 2 3]
 [4 5 6]]
two_dim_arr[0]: [1 2 3]


In [336]:
# To access the first integer (1), we have to index twice:
# first to get the single list,
# second time to get the integer

two_dim_arr[0][0]

np.int64(1)

`nparray` has an attribute called `shape`.

The shape of an array is the number of elements in each dimension.

We can access attributes of an object using dot `.` notation

In [26]:
simple_arr

array([1, 2, 3, 4, 5])

In [27]:
simple_arr.shape  # simple_arr has 1 dimension which has 5 elements

(5,)

In [24]:
two_dim_arr.shape  # two_dim has 2 dimensions; the first one has 2 elements and second has 3 elements
# Note that the number of dimensions is the number of integers listed (in this case, 2)

(2, 3)

In [25]:
new_array = np.array([[1, 2], [3, 4], [5, 6]])
new_array.shape  # the array has 2 dimensions, where the first dimension has 3 elements and the second has 2.

(3, 2)

In [29]:
# TODO: Create an array with numbers 1 to 5
my_array = ...

# TODO: Multiply the array by 2
doubled = ...

# Print to check
print(doubled)

Ellipsis
