# Data Analysis in Python with NumPy and Pandas

Before we can use libraries, we need to import them.

We use the abbreviations `np` and `pd` to make it easier to refer to these packages.

In [2]:
#@title Imports

import numpy as np
import pandas as pd

## The `numpy` array

Recall how to create a Python list:

In [3]:
list1 = [1, 2, 3, 4]

Use the `np.array` function to convert a Python list to a `ndarray`

In [4]:
array1 = np.array(list1)

print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


We start with a Python list (of lists) to create a 2D ndarray.

In [5]:
# TODO: Create a Python list called list2 that stores two lists [1, 2, 3] and [4, 5, 6]
list2 = ...

In [6]:
array2 = np.array(list2)

print(array2)
print(array2.shape)

Ellipsis
()


In [7]:
#@title Test cases (DO NOT EDIT)

assert np.array_equal(array2, np.array([[1, 2, 3], [4, 5, 6]])), f"Expected array2 to be [[1, 2, 3], [4, 5, 6]]. Was {array2}"

AssertionError: Expected array2 to be [[1, 2, 3], [4, 5, 6]]. Was Ellipsis

In [ ]:
# You can also create arrays like this:

array3 = np.array([[1, 2, 3], [4, 5, 6]])
print(array3)
print(array3.shape)
print(np.array_equal(array2, array3))

print("--------------------------------------------------")

array4 = np.array([
    [
        [1, 2, 3, 4],
        [4, 5, 6, 7],
        [8, 9, 10, 11]
    ],
    [
        [7, 8, 9, 10],
        [10, 11, 12, 13],
        [14, 15, 16, 17]
    ]
])
print(array4)
print("array4 is a 3D array")
print(array4.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
False
--------------------------------------------------
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 7  8  9 10]
  [10 11 12 13]
  [14 15 16 17]]]
array4 is a 3D array
(2, 3, 4)


When you have a NumPy array, you can use `.shape` to find out its size:

- `.shape` returns a **tuple** that shows how many rows and columns the array has
- The format is always `(rows, columns)` for 2D arrays

You can think of `.shape` as asking:

> "How big is this array?"

This is called **dot notation** because we access the attribute using a dot: `array.shape`.

Try the examples below and fill in the missing shapes.

In [ ]:
# TODO: Create an array with 2 rows and 2 columns
a = np.array(...)

# TODO: Create an array with 1 row and 3 columns
b = np.array(...)

# TODO: Create an array with 3 rows and 1 column
c = np.array(...)

In [ ]:
#@title Test cases (DO NOT EDIT)
assert a.shape == (2, 2), f"Expected a to be shape (2, 2). Was {a.shape}"
assert b.shape == (1, 3), f"Expected b to be shape (1, 3). Was {b.shape}"
assert c.shape == (3, 1), f"Expected c to be shape (3, 1). Was {c.shape}"

AssertionError: Expected a to be shape (2, 2). Was ()

### Timing comparisons: Python lists vs. ndarrays

We use ndarrays because it is much faster to perform calculations on them compared to Python lists.

Let's explore how the times differ for the same calculation on the same data for Python lists vs. ndarrays!
Run the code below multiple times :)

In [ ]:
import time

# Create a large dataset
size = 10_000_000
py_list = list(range(size))
np_array = np.arange(size)

# Timing: Multiply every element by 2

# Python list (using list comprehension)
start = time.time()
py_result = [x * 2 for x in py_list]  # This is the same as using a for loop
end = time.time()
list_time = end - start
print(f"Python list time: {list_time:.5f} seconds")

# NumPy array (vectorized)
start = time.time()
np_result = np_array * 2
end = time.time()
numpy_time = end - start
print(f"NumPy array time: {numpy_time:.5f} seconds")

# Comparison
speedup = list_time / numpy_time if numpy_time > 0 else float('inf')
print(f"NumPy is about {speedup:.2f}x faster than list comprehension.")


Python list time: 0.34501 seconds
NumPy array time: 0.01750 seconds
NumPy is about 19.72x faster than list comprehension.


## 🐼 Pandas DataFrame

A **DataFrame** is a table of data. It’s like a spreadsheet in Excel or Google Sheets, but in Python.

Each **row** is one record (like one person, one item, one event).  
Each **column** is a variable (like name, age, score, etc.).

You can:

- Create a DataFrame from a Python dictionary
- View the first few rows with `.head()`
- Access a column with `df["column_name"]`
- Get information about the data with `.info()` or `.describe()`

In [ ]:
# Create a DataFrame
data = {
    "Student": ["Ava", "Ben", "Cara", "Dan"],
    "Grade": [9, 8, 9, 8],
    "Math_Score": [95, 88, 76, 90]
}

df = pd.DataFrame(data)

df

Student  Grade  Math_Score
0     Ava      9          95
1     Ben      8          88
2    Cara      9          76
3     Dan      8          90

In [ ]:
# View the first few rows
print(df.head())

  Student  Grade  Math_Score
0     Ava      9          95
1     Ben      8          88
2    Cara      9          76
3     Dan      8          90


In [ ]:
# Access a single column
print("Math Scores:")
print(df["Math_Score"])

Math Scores:
0    95
1    88
2    76
3    90
Name: Math_Score, dtype: int64


In [ ]:
# Get summary statistics
print("Description:")
print(df.describe())

Description:
         Grade  Math_Score
count  4.00000    4.000000
mean   8.50000   87.250000
std    0.57735    8.057088
min    8.00000   76.000000
25%    8.00000   85.000000
50%    8.50000   89.000000
75%    9.00000   91.250000
max    9.00000   95.000000


In [ ]:
# Add a new column
df["Passed"] = df["Math_Score"] >= 80
df

Student  Grade  Math_Score  Passed
0     Ava      9          95    True
1     Ben      8          88    True
2    Cara      9          76   False
3     Dan      8          90    True

### Test Your Understanding

1. Create a DataFrame with this dictionary:

    ```python
    {
        "item": ["pencil", "notebook", "eraser"],
        "price": [1.5, 3.0, 0.75],
        "in_stock": [True, False, True]
    }
    ```

2. Use `.head()` to print the first few rows.
3. Add a new column called "discounted" that is `True` if the price is less than `2.0`.

In [ ]:
# TODO: Create a dictionary called store with keys: item, price, in_stock
store = ...

# TODO: Create a DataFrame called df with the dictionary store
df = ...

In [ ]:
# TODO: Call head on your data

In [ ]:
# TODO: Add new column discounted that is True if the price < 2.0

In [ ]:
#@title Test cases (DO NOT EDIT)
assert store == {
     "item": ["pencil", "notebook", "eraser"],
    "price": [1.5, 3.0, 0.75],
    "in_stock": [True, False, True]
}, "store dictionary is incorrect. Are dictionary keys lowercase?"
assert isinstance(df, pd.DataFrame), "df should be a DataFrame"
assert df.shape == (3, 4), f"Shape should be (3, 4). Was {df.shape}"
assert df["discounted"].tolist() == [True, False, True], "Discounted column values are incorrect"
assert "in_stock" in df.columns, "in_stock column missing"

AssertionError: store dictionary is incorrect. Are dictionary keys lowercase?

## Spotify Dataset: Scavenger Hunt

We are going to practice using Pandas with Spotify's Top Songs of 2023.

Dataset from [kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023](https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023).

In [8]:
# Create a DataFrame for Spotify
data_root = "https://github.com/rachelkd/geering-up/raw/refs/heads/main/data/"
spotify_df = pd.read_csv(data_root + "spotify-2023.csv", encoding="latin-1")

In [ ]:
# Convert object types to integer types
spotify_df["streams"] = pd.to_numeric(spotify_df["streams"], errors="coerce")
spotify_df["in_shazam_charts"] = pd.to_numeric(spotify_df["in_shazam_charts"], errors="coerce")

In [16]:
spotify_df.head()
spotify_df

track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2   
1                                   LALA         Myke Towers             1   
2                                vampire      Olivia Rodrigo             1   
3                           Cruel Summer        Taylor Swift             1   
4                         WHERE SHE GOES           Bad Bunny             1   
..                                   ...                 ...           ...   
948                         My Mind & Me        Selena Gomez             1   
949            Bigger Than The Whole Sky        Taylor Swift             1   
950                 A Veces (feat. Feid)  Feid, Paulo Londra             2   
951                        En La De Ella  Feid, Sech, Jhayco             3   
952                                Alone           Burna Boy             1   

     released_year  released_month  released_day  in_spotify_playlists  \
0             2023               7            14                   553   
1             2023               3            23                  1474   
2             2023               6            30                  1397   
3             2019               8            23                  7858   
4             2023               5            18                  3133   
..             ...             ...           ...                   ...   
948           2022              11             3                   953   
949           2022              10            21                  1180   
950           2022              11             3                   573   
951           2022              10            20                  1320   
952           2022              11             4                   782   

     in_spotify_charts      streams  in_apple_playlists  ...  bpm key   mode  \
0                  147  141381703.0                  43  ...  125   B  Major   
1                   48  133716286.0                  48  ...   92  C#  Major   
2                  113  140003974.0                  94  ...  138   F  Major   
3                  100  800840817.0                 116  ...  170   A  Major   
4                   50  303236322.0                  84  ...  144   A  Minor   
..                 ...          ...                 ...  ...  ...  ..    ...   
948                  0   91473363.0                  61  ...  144   A  Major   
949                  0  121871870.0                   4  ...  166  F#  Major   
950                  0   73513683.0                   2  ...   92  C#  Major   
951                  0  133895612.0                  29  ...   97  C#  Major   
952                  2   96007391.0                  27  ...   90   E  Minor   

     danceability_%  valence_% energy_% acousticness_%  instrumentalness_%  \
0                80         89       83             31                   0   
1                71         61       74              7                   0   
2                51         32       53             17                   0   
3                55         58       72             11                   0   
4                65         23       80             14                  63   
..              ...        ...      ...            ...                 ...   
948              60         24       39             57                   0   
949              42          7       24             83                   1   
950              80         81       67              4                   0   
951              82         67       77              8                   0   
952              61         32       67             15                   0   

     liveness_%  speechiness_%  
0             8              4  
1            10              4  
2            31              6  
3            11             15  
4            11              6  
..          ...            ...  
948           8              3  
949          12              6  
950      

In [15]:
# See the names of columns and their datatypes (dtypes)
spotify_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   track_name            953 non-null    object 
 1   artist(s)_name        953 non-null    object 
 2   artist_count          953 non-null    int64  
 3   released_year         953 non-null    int64  
 4   released_month        953 non-null    int64  
 5   released_day          953 non-null    int64  
 6   in_spotify_playlists  953 non-null    int64  
 7   in_spotify_charts     953 non-null    int64  
 8   streams               952 non-null    float64
 9   in_apple_playlists    953 non-null    int64  
 10  in_apple_charts       953 non-null    int64  
 11  in_deezer_playlists   953 non-null    object 
 12  in_deezer_charts      953 non-null    int64  
 13  in_shazam_charts      896 non-null    float64
 14  bpm                   953 non-null    int64  
 15  key                   8

### Task: Which rows/records have missing values?

In [ ]:
# spotify_df.isnull() returns a DataFrame of the same shape, with True where values are missing
spotify_df.isnull()

track_name  artist(s)_name  artist_count  released_year  released_month  \
0         False           False         False          False           False   
1         False           False         False          False           False   
2         False           False         False          False           False   
3         False           False         False          False           False   
4         False           False         False          False           False   
..          ...             ...           ...            ...             ...   
948       False           False         False          False           False   
949       False           False         False          False           False   
950       False           False         False          False           False   
951       False           False         False          False           False   
952       False           False         False          False           False   

     released_day  in_spotify_playlists  in_spotify_charts  streams  \
0           False                 False              False    False   
1           False                 False              False    False   
2           False                 False              False    False   
3           False                 False              False    False   
4           False                 False              False    False   
..            ...                   ...                ...      ...   
948         False                 False              False    False   
949         False                 False              False    False   
950         False                 False              False    False   
951         False                 False              False    False   
952         False                 False              False    False   

     in_apple_playlists  ...    bpm    key   mode  danceability_%  valence_%  \
0                 False  ...  False  False  False           False      False   
1                 False  ...  False  False  False           False      False   
2                 False  ...  False  False  False           False      False   
3                 False  ...  False  False  False           False      False   
4                 False  ...  False  False  False           False      False   
..                  ...  ...    ...    ...    ...             ...        ...   
948               False  ...  False  False  False           False      False   
949               False  ...  False  False  False           False      False   
950               False  ...  False  False  False           False      False   
951               False  ...  False  False  False           False      False   
952               False  ...  False  False  False           False      False   

     energy_%  acousticness_%  instrumentalness_%  liveness_%  speechiness_%  
0       False           False               False       False          False  
1       False           False               False       False          False  
2       False           False               False       False          False  
3       False           False               False       False          False  
4       False           False               False       False          False  
..        ...             ...                 ...         ...            ...  
948     False           False               False       False          False  
949     False           False               False       False          False  
950     False           False               False       False          False  
951     False           False               False       False          False  
952     False           False               False       False          False  

[953 rows x 24 columns]

In [20]:
# TODO: Use .sum() on the DataFrame that .isnull() returns to see how many samples of each column are missing
val_missing = ...

val_missing

Ellipsis

In [ ]:
# TODO: Which columns have missing values?
# Write answer as a list of strings where the strings are the names of the columns

answer = [...]

In [ ]:
#@title Test cases (DO NOT EDIT)
expected = ["in_shazam_charts", "key", "streams"]

assert isinstance(answer, list), "Answer must be a list"
assert sorted(answer) == sorted(expected), "Answer has the incorrect keys"

print("Task 1 passed!")

AssertionError: Answer has the incorrect keys

### Task: Filtering Rows Based on Column Value

Practice Boolean indexing to select rows using conditions.

In Pandas, `DataFrame[condition]` is how we filter rows.
The condition returns a mask (a Series of True/False), and only rows with True are kept.

In [ ]:
# TODO: Create a DataFrame popular_songs that contains only rows from spotify_df with 10 million or more streams
# Hint: spotify_df["streams"] >= 10_000_000 creates a Boolean Series (a list of True or False values)
popular_songs = ...

In [ ]:
#@title Test cases (DO NOT EDIT)
assert 'popular_songs' in globals(), "popular_songs must be defined"
assert isinstance(popular_songs, type(spotify_df)), "popular_songs should be a DataFrame"
assert (popular_songs['streams'] >= 10_000_000).all(), "Every song should have popularity >= 95"

print("Task 2 passed!")

AssertionError: popular_songs should be a DataFrame

### Task: Grouping and Aggregation

Use `.groupby()` to analyze data by categories, such as seeing how many songs each artist has in the dataset.

In [ ]:
# TODO: Get the top 10 artists that show up most frequently in the dataset
# Hint: .groupby("artist(s)_name") groups the DataFrame by each unique value in the "artist(s)_name" column.
# Each group contains all rows (songs) by a single artist.
# After grouping, select the "track_name" column for each group. This narrows the grouped data down to just the song names.
# Use .count() to count the non-null song names for each artist
# Use .sort
# Use .head(n) to select the first 10 (make sure to set function args correctly)


most_freq_artists = ...

print(most_freq_artists)
print("--------------------")
print(most_freq_artists.name)  # should tell us what we are counting
print(most_freq_artists.index.name)  # should tell us what the keys mean

artist(s)_name
Taylor Swift        34
The Weeknd          22
SZA                 19
Bad Bunny           19
Harry Styles        17
Kendrick Lamar      12
Morgan Wallen       11
Ed Sheeran           9
Drake, 21 Savage     8
BTS                  8
Feid                 8
Name: track_name, dtype: int64
--------------------
track_name
artist(s)_name


In [81]:
#@title Test cases (DO NOT EDIT)
expected = spotify_df.groupby("artist(s)_name")["track_name"].count().sort_values(ascending=False).head(10)

assert isinstance(most_freq_artists, pd.Series), "most_freq_artists should be a Series"
assert most_freq_artists.name in ['track_name'], "Series name should be track_name"
assert most_freq_artists.index.name in ['artist(s)_name'], "Series index should be artist"

try:
    pd.testing.assert_series_equal(most_freq_artists, expected)
    print("Task 3 passed!")
except AssertionError:
    raise AssertionError(f"Incorrect series.\n\nExpected:\n{expected}.\n\nGot:\n{most_freq_artists}") from None


AssertionError: Incorrect series.

Expected:
artist(s)_name
Taylor Swift        34
The Weeknd          22
SZA                 19
Bad Bunny           19
Harry Styles        17
Kendrick Lamar      12
Morgan Wallen       11
Ed Sheeran           9
Drake, 21 Savage     8
BTS                  8
Name: track_name, dtype: int64.

Got:
artist(s)_name
Taylor Swift        34
The Weeknd          22
SZA                 19
Bad Bunny           19
Harry Styles        17
Kendrick Lamar      12
Morgan Wallen       11
Ed Sheeran           9
Drake, 21 Savage     8
BTS                  8
Feid                 8
Name: track_name, dtype: int64

### Task: Sorting Rows
Order your DataFrame using .sort_values(), e.g., to see top results.

In [ ]:
# TODO: Create sorted_by_most_streams that has rows of spotify_df sorted descending (greatest to least)
# for streams
sorted_by_most_streams = ...

sorted_by_most_streams

In [93]:
# TODO: What was the most streamed song in 2023?
# Write your answer as a string

answer = ...

In [94]:
#@title Test Cases (DO NOT EDIT)
expected = "blinding lights"

assert answer.lower() == expected, "Not the right song!"

AttributeError: 'ellipsis' object has no attribute 'lower'

### Solutions

In [83]:
# Task 1
answer = ["key", "in_shazam_charts"]
# Task 2
popular_songs = spotify_df[spotify_df["streams"] >= 10_000_000]
# Task 3
most_freq_artists = spotify_df.groupby("artist(s)_name")["track_name"].count().sort_values(ascending=False).head(10)
# Task 4
sorted_by_most_streams = spotify_df.sort_values(by="streams", ascending=False)
